Refactor/server checks answers
samuelgagnon/MathEnJeu pull request #47
Opened 2021-02-04 18:47 UTC by samuelgagnon

2021-02-05 20:24 UTC, Jpbureau requested changes
Les quelques points que j'ai soulevés sont:

- Possible refactor pour l'utilisation des sockets (on s'en parlera plus en détails, j'ai quelques idées pour ça)
- L'attribut _isRight, je ne crois pas que c'est une bonne idée qu'elle peut être null
- Si jamais on Map pas la réponse, on pourra enlever la méthode car on l'utilise nul part ailleurs

Overall je crois qu'on devra faire quelques changements, il y a beaucoup de complexité qu'on peut sûrement éviter dans la QuestionScene (je crois, je suis pas certain) et les problèmes que j'ai mentionné, mais sinon j'aime l'idée que le serveur valide la réponse du client.

2021-02-05 20:24 UTC, Jpbureau commented on game/src/gameCore/race/question/Answer.ts
> +	constructor(id: number, label: string, isRight?: boolean) {
En disant que le paramètre peut être null, c'est quand même dangereux parce qu'on a une méthode qui retourne _isRight directement. On peut donc avoir une valeur null. J'aime vraiment pas trop ce choix puisqu'on a aucune manière de savoir si l'objet Answer a l'attribut isRight ou non. Il faudrait au minimum mettre un "?" à l'attribut private, mais on a quand même le problème avec la méthode qui est supposé retourner un bool car elle peut retourner null.

2021-02-05 20:24 UTC, Jpbureau commented on game/src/gameCore/race/question/Answer.ts
>  		return {
Ici on aurait plus besoin de regarder la ligne 33 étant donné qu'on enlève isRight du DTO.

2021-02-05 20:24 UTC, Jpbureau commented on game/src/gameCore/race/player/Player.ts
> +	public givePenalty(): void {
Parenthèse comme ça, je sais que dans l'ancien jeu on avait une pénalité qui augmentait avec le nombre de questions manquées. Il serait quand même très facile de rajouter cette fonctionnalité là avec cette implémentation là.

2021-02-05 20:24 UTC, Jpbureau commented on game/src/gameCore/race/ServerRaceGameController.ts
> +						const clientAnswer: Answer = QuestionMapper.mapAnswer((<QuestionAnsweredEvent>inputData).answer);
Je vois pas trop l'utilité de Map le DTO à un objet Answer dans ce cas si parce qu'on a tous les éléments qu'on souhaite avoir. Je crois que les "best practices" disent toujours de Map vers les objets du domaine, mais bon je lance la question.

2021-02-05 20:24 UTC, Jpbureau commented on game/src/gameCore/race/ServerRaceGameController.ts
> +								correspondingAnswer.isRight() ||
Un exemple du problème que je parlais du fait que l'attribut _isRight de la classe Answer peut se produire ici. Si isRight est null, même si c'est effectivement la bonne réponse, answerIsRight peut avoir être "null". Je sais qu'en théorie le serveur garde _isRight comme booléen, mais ça peut créer des bugs vraiment pas évidents.

2021-02-05 20:24 UTC, Jpbureau commented on game/src/gameCore/race/ClientRaceGameController.ts
> +			this.playerAnsweredQuestion(data.answerIsRight, data.targetLocation, this.currentPlayerId, data.correctionTimestamp);
Comme on en avait parlé, je sais pas si on devrait mettre un socket event additionnel dans l'interface juste pour notifier.

2021-02-05 20:24 UTC, Jpbureau commented on game/src/client/scenes/QuestionScene.ts
> +		if (!raceGame.getCurrentPlayer().isAnsweringQuestion()) {
J'ai fait un commentaire là dessus dans ClientRaceGameController, mais peut-être qu'on pourrait mettre un socket qui écoute aussi dans la scene Question, ce qui permettrait probablement de simplifier un peu la la scène ici et la classe Player.

2021-02-08 14:56 UTC, samuelgagnon commented on game/src/client/scenes/QuestionScene.ts
> +			} else {
J'vais corriger ça ;)

2021-02-08 15:02 UTC, samuelgagnon commented on game/src/gameCore/race/question/Answer.ts
> +	constructor(id: number, label: string, isRight?: boolean) {
Voici mes idées : 
1. Je pourrais changer isRight par "knownAsRight". Comme ça, côté client, ça serait toujours false, et côté serveur, y'aurait une réponse où "knownAsRight" serait à True. La méthode deviendrait "isKnownAsRight".
2. Je laisse isRight comme il est avec un ajout de ? à l'attribut. Il peut donc être null/undefined (à voir). Ensuite, je change le nom de l'attribut pour "isKnownAsRight" qui retourne true or false et jamais "null/undefined".

@Jpbureau As-tu une préférence?

2021-02-08 15:12 UTC, samuelgagnon commented on game/src/gameCore/race/ServerRaceGameController.ts
> +						const clientAnswer: Answer = QuestionMapper.mapAnswer((<QuestionAnsweredEvent>inputData).answer);
Je vais voir ce qu'on peut faire!

2021-02-08 15:15 UTC, samuelgagnon commented on game/src/gameCore/race/ClientRaceGameController.ts
> +			this.playerAnsweredQuestion(data.answerIsRight, data.targetLocation, this.currentPlayerId, data.correctionTimestamp);
Yep! Mais en même temps, comme est pour refactor le frontend, j'sais pas si ça vaut la peine que je modifie ça dans cette branche?

2021-02-08 15:15 UTC, samuelgagnon commented on game/src/client/scenes/QuestionScene.ts
> +		if (!raceGame.getCurrentPlayer().isAnsweringQuestion()) {
Yep! Mais en même temps, comme est pour refactor le frontend, j'sais pas si ça vaut la peine que je modifie ça dans cette branche?

2021-02-09 10:25 UTC, samuelgagnon commented on game/src/gameCore/race/question/Answer.ts
> +	constructor(id: number, label: string, isRight?: boolean) {
J'ai choisi l'option 1.

2021-02-09 10:25 UTC, samuelgagnon commented on game/src/client/scenes/QuestionScene.ts
> +			} else {
done

2021-02-09 10:25 UTC, samuelgagnon commented on game/src/gameCore/race/question/Answer.ts
>  		return {
done

2021-02-09 10:34 UTC, samuelgagnon commented on game/src/gameCore/race/ServerRaceGameController.ts
> +						const clientAnswer: Answer = QuestionMapper.mapAnswer((<QuestionAnsweredEvent>inputData).answer);
Effectivement, en relisant j'me rend compte que les infos de la DTO sont entièrement suffisantes pour ce qu'on en fait. J'ai apporté les changements.

2021-02-09 10:37 UTC, samuelgagnon commented on game/src/gameCore/race/ServerRaceGameController.ts
> +								correspondingAnswer.isRight() ||
J'ai changé isRight par isKnownAsRight. 
isKnownAsRight retourne TOUJOURS vrai ou faux (jamais null/undefined).

2021-02-09 11:22 UTC, samuelgagnon commented on game/src/gameCore/race/ClientRaceGameController.ts
> +			this.playerAnsweredQuestion(data.answerIsRight, data.targetLocation, this.currentPlayerId, data.correctionTimestamp);
Je ne peux pas inscrire à la fois QuestionScene et ClientRaceGameController à l'événement CE.ANSWER_CORRECTED. La raison est fort simple : ClientRaceGameController doit résoudre ses actions en réponse à ANSWER_CORRECTED avant que QuestionScene débute sa résolution.

Pour le moment, afin de simplifier le code dans la loop d'update de QuestionScene, j'ai décidé de donner l'entière responsabilité pour l'écoute de l'event à QuestionScene. Je pense qu'il sera plus facile à partir de là de refactor.

2021-02-09 11:29 UTC, samuelgagnon commented on game/src/client/scenes/QuestionScene.ts
> +		if (!raceGame.getCurrentPlayer().isAnsweringQuestion()) {
Je vais copier-coller mon précédent commentaire :
Je ne peux pas inscrire à la fois QuestionScene et ClientRaceGameController à l'événement CE.ANSWER_CORRECTED. La raison est fort simple : ClientRaceGameController doit résoudre ses actions en réponse à ANSWER_CORRECTED avant que QuestionScene débute sa résolution.

Pour le moment, afin de simplifier le code dans la loop d'update de QuestionScene, j'ai décidé de donner l'entière responsabilité pour l'écoute de l'event à QuestionScene. Je pense qu'il sera plus facile à partir de là de faire le refactor frontend.

2021-02-09 15:32 UTC, merged