Feature/private rooms
samuelgagnon/MathEnJeu pull request #54
Opened 2021-02-18 00:02 UTC by Jpbureau

Il est possible maintenant de choisir si la room est public ou private. J'ai séparé la scène "roomSelectionScene" en 3 différentes scènes. Une pour les options de création de la room, une pour la sélection de partie publique et une pour le choix de création/public/private. 

Comme je l'ai mentionné, regarde comment j'ai géré les sockets entre chaque scène, si t'as une meilleure idée amène là !

Finalemement, quelques éléments que je n'ai pas encore implémentés sont:
- Génération de code facile à partager pour les room privées
- Changement dynamique du type (private/public) des room une fois créées

2021-02-18 13:29 UTC, samuelgagnon commented
Étape 1, avant même de regarder le code, j'suis allé essayer la feature ;).
Le concept de "private room" semble fonctionner! Je ne trouvais pas comment tester la feature parce qu'on ne voit pas explicitement le code de la room quand on se crée un room private, donc j'me suis ajouté un console.log et avec ça j'ai pu voir que ça fonctionnait bien 👍 .

Sinon, à date, j'ai trouvé deux bugs qui se reproduisent facilement : 
1. Quand on se crée un game seul, qu'on start la game seul et qu'on quitte, on reçoit une erreur (apparement lié au socket) côté client. J'ai aussi eu le bug en faisant une game privées avec 2 joueurs. Quand j'ai voulu quitter, les deux joueurs ont eu une erreur.
2. Quand un joueur participe à une game publique, il ne peut plus créer ni rejoindre d'autres parties.

Il y aura donc des changements à apporter ;). Ceci étant, j'vais aller voir un peu plus en détail la logique générale du code.

2021-02-18 13:48 UTC, samuelgagnon requested changes
Avant même de regarder le code, j'suis allé essayer la feature ;).
Le concept de "private room" semble fonctionner! Je ne trouvais pas comment tester la feature parce qu'on ne voit pas explicitement le code de la room quand on se crée un room private, donc j'me suis ajouté un console.log et avec ça j'ai pu voir que ça fonctionnait bien 👍 .

Sinon, à date, j'ai trouvé deux bugs qui se reproduisent facilement :

Quand on se crée un game seul, qu'on start la game seul et qu'on quitte, on reçoit une erreur (apparement lié au socket) côté client. J'ai aussi eu le bug en faisant une game privées avec 2 joueurs. Quand j'ai voulu quitter, les deux joueurs ont eu une erreur.
Quand un joueur participe à une game publique, il ne peut plus créer ni rejoindre d'autres parties.
Il y aura donc des changements à apporter ;). Ceci étant, j'vais aller voir un peu plus en détail la logique générale du code.

Après que tu aies réglé ces bugs, j'aimerais ça qu'on se jase un peu de ta philosophie pour la gestion des sockets et les changements liés juste pour être certain que j'comprends bien ta logique.

2021-02-18 13:48 UTC, samuelgagnon commented on game/src/server/rooms/Room.ts
>  	private max_player_count = 51;
J'vois que la *feature* pour limiter le nombre de joueurs dans une room a été faite, mais pas à 100%. Pas de trouble à ce que ça soit complété dans une autre PR, mais j'ai fait une carte Trello à ce propos pour être certain qu'on ne l'oublie pas.

2021-02-18 22:19 UTC, Jpbureau commented
J'ai changé la connection vers une méthode et j'ai changé la connection vers une méthode qui peut être utilisée ou non dépendemment de si on en a besoin ou non

2021-02-19 13:10 UTC, samuelgagnon approved these changes
Good job! 👍

2021-02-19 13:10 UTC, merged