Bugfix/avoid negative game time
samuelgagnon/MathEnJeu pull request #56
Opened 2021-02-19 19:41 UTC by samuelgagnon

2021-02-19 22:50 UTC, Jpbureau reviewed
J'ai seulement regardé le code, mais je vais tester plus en profondeur lundi matin !

2021-02-19 22:50 UTC, Jpbureau commented on game/src/client/Localization.ts
> +}
Il faudra voir possiblement un système qui inject le bon texte en fonction de la langue sans avoir à toujours dit "if anglais then, if français then",

2021-02-19 22:50 UTC, Jpbureau commented on game/src/client/scenes/raceGame/RaceScene.ts
> +			if (!!!data.error) {
dans ce cas-ci on peut mettre if(data.error). Ce qui veut pretty much dire "si ça existe". Je sais qu'ailleurs j'avais mis les !!! mais ça semblait pas marcher pour mon cas (si jme souviens bien***) Sinon je vais le changer 😋

2021-02-19 22:50 UTC, Jpbureau commented on game/src/server/rooms/RoomManager.ts
> -					});
Comme je l'ai mentionné on peut recevoir l'erreur avec 
socket.on("error", (e) => {
 //code
})

2021-02-19 22:50 UTC, Jpbureau commented on game/src/server/rooms/RoomManager.ts
> +			socket.on(ROOM_EVENT_NAMES.JOIN_ROOM_REQUEST, (req) => {
Je sais c'est picky, mais peut-être qu'on pourrait mettre un type spécifique pour ce type de request là. Comme ça on sait exactement avec quoi on travaille.

2021-02-22 12:58 UTC, samuelgagnon commented on game/src/server/rooms/RoomManager.ts
> +			socket.on(ROOM_EVENT_NAMES.JOIN_ROOM_REQUEST, (req) => {
J'ai ajouté un dataInterface pour le join room request.

2021-02-22 13:05 UTC, samuelgagnon commented on game/src/client/scenes/raceGame/RaceScene.ts
> +			if (!!!data.error) {
J'ai changé cette section pour que ça soit plus claire.

2021-02-22 13:19 UTC, samuelgagnon commented on game/src/client/Localization.ts
> +}
C'est au travers de recherches de gestion de "localization" en typescript, que j'étais tombé sur cette solution.
L'idée est d'utiliser l'interface comme ceci (j'ai ajouté des langues comme exemple montrer l'idée plus générale) :
`const language = "esp";`
`const message = <localizedString>{fra: "Salut", eng: "Hi", esp: "Hola", ita: "Ciao"};`
`console.log(message[language]);`
Output : Hola

J'suis pas contre l'idée d'utiliser un autre système si y'a mieux... par contre je ne sais pas ce que tu veux dire exactement ici par "système d'injection" ;) .

2021-02-22 16:49 UTC, Jpbureau requested changes
Juste le petit commentaire sinon c'est good !

2021-02-22 16:49 UTC, Jpbureau commented on game/src/communication/room/EventNames.ts
> +	JOIN_ROOM_ANSWER: "room-joined",
Je crois qu'on devrait changer la string pour resté cohérent et garder une structure similaire.

2021-02-22 16:49 UTC, Jpbureau commented on game/src/client/scenes/BaseScene.ts
> +			}
On pourra mettre un event quelconque de phaser et une scène qui regarde les erreur et affiche le texte en conséquence.

2021-02-22 16:49 UTC, Jpbureau commented on game/src/server/rooms/RoomManager.ts
> +						error = new Error("Unexpected error : " + JSON.stringify(e));
Je ne crois pas que c'est nécessaire de s'assurer que c'est de type Error.

2021-02-22 21:03 UTC, merged